# Generated by go2rpm 1.5.0
%bcond_without check

# https://github.com/klauspost/cpuid
%global goipath         github.com/klauspost/cpuid/v2
Version:                2.0.9

%gometa

%global common_description %{expand:
CPU feature identification for Go.}

%global golicenses      LICENSE
%global godocs          CONTRIBUTING.txt README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        CPU feature identification for Go

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc CONTRIBUTING.txt README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Sun Sep 05 2021 Petr Menšík <pemensik@redhat.com> - 2.0.9-1%{?dist}
- Initial package

